language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-25.0.2
    - extra-android-support
    - extra-android-m2repository
    - android-25
  licenses:
    - '.+'
