language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-24.0.3
    - extra-android-support
    - extra-android-m2repository
    - android-24
  licenses:
    - '.+'
