language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - build-tools-27.0.3
    - extra-android-support
    - extra-android-m2repository
    - android-27
  licenses:
    - '.+'
before_install:
  - yes | sdkmanager "platforms;android-27"
  - ./gradlew clean assemble -S
